# fly.toml app configuration file generated for tournament-form-jujo on 2025-10-15T20:41:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tournament-form-jujo'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
